[package]
name = "usbfs-device"
version = "0.1.0"
authors = ["David Holroyd <dave@badgers-in-foil.co.uk>"]
edition = "2018"

[dependencies]
nix = "0.12"
usbfs-sys = { path = "../usbfs-sys" }
bitflags = "1.0"
byteorder = "1.2"
mio = "0.6"
tokio = "0.1"
futures = "0.1"
